language: node_js
node_js:
  - 'node'
install:
  - yarn
script:
  - yarn test
  - yarn lint
  - yarn type
before_deploy:
  - yarn build
deploy:
  - provider: npm
    skip_cleanup: true
    email: simon.schwartz0@gmail.com
    api_key:
      secure: "keVcAYssXmAoW/oyH456S701y85XS05W8HUXgeFULnJF1LgZZNyIiPD7K0gDsc11R0wQmu14NSy9C5HTCAFtOpaqAzfuhvImSH8tQ/9Z/IY3Vtg26ynVyhU44yw33Xpi6sp+Ue3q0O4lEkKY0i7GzJMxYpc1OYgbjIXVkwD9yFru8Oous3ck7+30KrkPuf/E0fYThLAMed1UDu/xKOwDhriZfj6odg3aPjQVWgmqZyH+04BxukehYsxgl5uAe8Bzkj8SehgAZyQ906px+KDGFq402oqC+cW3nNhulyICdLd8E5h+/IfPw+a/9PWZ6aOqoLrEcLvF+CnAx+2YoAIGR+tojSXQoOGOb5cxAcDmAce1PpNs8mlwR19Zih3zohxzyY83xV1INjNhS+XomdUNK00DKvXrI1SSEhcvWKhkRKqH96wazOZOoWx8azST2MRfBy+O5d1A6nJMn2rLEdsyVcHUsIsxUHVRXkx2HaxKzmbeGReuOg6SH9u4UkTlRzlMw6tT9IDzEDayy4lQcTFr5TzzBXsjCZXJ83JEnjryTGiQLVlJ8i728X+emcIySKYK4KC26AOkxNedvcY5yIIoeIRcjvs2EOmq40//DBT/BQcw7DD5UGjTTh6taYh8jLjMujD6Yq60ns0THXrKH4oNJT4He1jX0SoLvdMMAb78lZQ="
    on:
      tags: true
      branch: master